# Use 'true' para MySQL e 'false' para SQLite.
MySQL: false
mysql:
  host: "localhost"
  port: "3306"
  database: "minecraft"
  username: "root"
  password: ""
# Configuração de passes, quantos terão? Max: 5.
permissionsCount: 2
names:
  - gratuito
  - premium
# Max de missões: 53.
missoes:
  andar:
    # Use: TO_WALK, BREAK_BLOCK, PUT_BLOCK, KILL_MOBS, KILL_PLAYER ou ONLINE_TIME.
    type: TO_WALK
    # Quantos blocos ele vai andar?
    distance: 250
    # Vão pode refazer a missão?
    repeat: false
    # Deixe '[]' para qualquer mundo
    worlds: []
     #- aventure
  quebrar:
    # Use: TO_WALK, BREAK_BLOCK, PUT_BLOCK, KILL_MOBS, KILL_PLAYER ou ONLINE_TIME.
    type: BREAK_BLOCK
    # Quantos blocos?
    amount: 300
    # Qual bloco?
    material: OAK_LOG
    # Vão pode refazer a missão?
    repeat: false
    # Deixe '[]' para qualquer mundo
    worlds: [ ]
    #- aventure
  colocar:
    # Use: TO_WALK, BREAK_BLOCK, PUT_BLOCK, KILL_MOBS, KILL_PLAYER ou ONLINE_TIME.
    type: PUT_BLOCK
    # Quantos blocos?
    amount: 200
    # Qual bloco?
    material: GRASS_BLOCK
    # Vão pode refazer a missão?
    repeat: false
    # Deixe '[]' para qualquer mundo
    worlds: [ ]
    #- aventure
  matarmobs:
    # Use: TO_WALK, BREAK_BLOCK, PUT_BLOCK, KILL_MOBS, KILL_PLAYER ou ONLINE_TIME.
    type: KILL_MOBS
    # Quantos mobs?
    amount: 200
    mob: ZOMBIE
    # Vão pode refazer a missão?
    repeat: false
    # Deixe '[]' para qualquer mundo
    worlds: [ ]
    #- aventure
  matarplayers:
    # Use: TO_WALK, BREAK_BLOCK, PUT_BLOCK, KILL_MOBS, KILL_PLAYER ou ONLINE_TIME.
    type: KILL_PLAYER
    # Quantos jogadores?
    amount: 20
    # Vão pode refazer a missão?
    repeat: false
    # Deixe '[]' para qualquer mundo
    worlds: [ ]
    #- aventure
  temponline:
    # Use: TO_WALK, BREAK_BLOCK, PUT_BLOCK, KILL_MOBS, KILL_PLAYER ou ONLINE_TIME.
    type: ONLINE_TIME
    # Quanto tempo em minutos?
    time: 300
    # Vão pode refazer a missão?
    repeat: false