# Configuração do plugin
MySQL: false  # Use 'true' para MySQL e 'false' para SQLite
# Configuração do banco de dados para MySQL
mysql:
  host: "localhost"
  port: "3306"
  database: "minecraft"
  username: "root"
  password: ""
# Configuração do banco de dados para SQLite
sqlite:
  file: "plugins/LIZPasse/db.sqlite"  # Caminho para o arquivo SQLite
# Outras configurações do plugin (por exemplo, configurações de passes, missões, etc.)
passe:
  info_lore:
    - "§7Você tem o passe §6#1"
    - "§7Complete missões para obter recompensas!"
    - "§7Para obter outro passe, fale com o NPC."
# Configuração de cooldowns para missões
cooldowns:
  default: "1d"  # Cooldown padrão de 1 dia
missions:
  mission_1:
    name: "Caçador de Mobs"
    description: "Mate 10 mobs de qualquer tipo"
    type: "kill_mobs"
    target: 10
    cooldown: "1d"  # 1 dia de cooldown entre a conclusão da missão
  mission_2:
    name: "Destruidor"
    description: "Quebre 20 blocos"
    type: "break_blocks"
    target: 20
    cooldown: "1d"
  mission_3:
    name: "Construtor"
    description: "Coloque 10 blocos de pedra"
    type: "place_blocks"
    target: 10
    cooldown: "1d"
  mission_4:
    name: "Corredor"
    description: "Ande 500 blocos"
    type: "move"
    target: 500
    cooldown: "1d"
  mission_5:
    name: "Mensageiro"
    description: "Envie 10 mensagens no chat"
    type: "send_messages"
    target: 10
    cooldown: "1d"
  mission_6:
    name: "PvP Master"
    description: "Mate 5 jogadores"
    type: "kill_players"
    target: 5
    cooldown: "1d"
